[package]
name = "coinbot_mastodon"
version = "0.1.0"
authors = ["ChanHwi, Choi (aka Ch.) <ccwpc@hanmail.net>"]

[dependencies]
mammut = "0.11.0"
serde = "1.0.79"
serde_derive = "1.0.79"
toml = "0.4"
reqwest = "0.9.2"
serde_json = "1.0"
separator = "0.3.1"