[package]
name = "coinbot_mastodon"
version = "0.1.1"
authors = ["ChanHwi, Choi (aka Ch.) <ccwpc@hanmail.net>"]

[dependencies]
mammut = "0.12"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
reqwest = "0.9"
serde_json = "1.0"
separator = "0.4"